// Generated by CoffeeScript 1.3.3
(function() {

  define(function(require) {
    var util;
    return util = {
      distance: function(a, b) {
        var dx, dy;
        dx = a.x - b.x;
        dy = a.y - b.y;
        return Math.sqrt(dx * dx + dy * dy);
      },
      nearestBorder: function(centerPosition, radius, otherPosition) {
        var alpha, dx, dy, x, y;
        dx = otherPosition.x - centerPosition.x;
        dy = centerPosition.y - otherPosition.y;
        alpha = Math.atan(dy / dx);
        x = Math.cos(alpha) * radius;
        y = Math.sin(alpha) * radius;
        if (centerPosition.x > otherPosition.x || centerPosition.y < otherPosition.y) {
          x = x * -1;
          y = y * -1;
        }
        if (centerPosition.x <= otherPosition.x && centerPosition.y < otherPosition.y) {
          x = x * -1;
          y = y * -1;
        }
        return {
          x: centerPosition.x + x,
          y: centerPosition.y - y
        };
      }
    };
  });

}).call(this);
