// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var Backbone, FleetView;
    Backbone = require('backbone');
    return FleetView = (function(_super) {

      __extends(FleetView, _super);

      function FleetView() {
        return FleetView.__super__.constructor.apply(this, arguments);
      }

      FleetView.prototype.initialize = function(opts) {
        this.gameView = opts.gameView;
        this.model.bind('change', this.render, this);
        this.model.bind('destroy', this.remove, this);
        this.el = this.gameView.paper.circle();
        this.strengthText = this.gameView.paper.text(-100, -100, this.model.get('strength'));
        return this.start();
      };

      FleetView.prototype.render = function() {
        return this.strengthText.attr({
          text: this.model.get('strength')
        });
      };

      FleetView.prototype.size = function() {
        var rad;
        rad = function(size) {
          return -0.0005 * size ^ 2 + 0.3 * size;
        };
        if (this.model.get('strength') < 200) {
          return rad(this.model.get('strength'));
        } else {
          return rad(200);
        }
      };

      FleetView.prototype.timeInFlight = function() {
        return this.gameView.model.ticksToTime(this.model.flightTime());
      };

      FleetView.prototype.start = function() {
        var disappear,
          _this = this;
        this.strengthText.attr({
          font: '12px Arial',
          stroke: 'none',
          fill: 'black',
          x: Math.round(this.model.startPosition().x),
          y: Math.round(this.model.startPosition().y - 10)
        });
        this.strengthText.animate({
          x: Math.round(this.model.endPosition().x),
          y: Math.round(this.model.endPosition().y - 10)
        }, this.timeInFlight());
        this.el.attr({
          r: this.size(),
          fill: this.model.get('owner').get('color'),
          cx: Math.round(this.model.startPosition().x),
          cy: Math.round(this.model.startPosition().y)
        });
        this.el.animate({
          cx: Math.round(this.model.endPosition().x),
          cy: Math.round(this.model.endPosition().y)
        }, this.timeInFlight());
        if (this.timeInFlight() > 500) {
          this.el.attr({
            r: 0
          });
          this.el.animate({
            r: this.size()
          }, 200, 'bounce');
          disappear = function() {
            return _this.el.animate({
              r: 0
            }, 200, 'bounce');
          };
          setTimeout(disappear, this.timeInFlight() - 200);
        }
        return this;
      };

      FleetView.prototype.remove = function() {
        this.el.remove();
        return this.strengthText.remove();
      };

      return FleetView;

    })(Backbone.View);
  });

}).call(this);
