// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var App, Backbone, Game;
    Game = require('./Game');
    Backbone = require('backbone');
    return App = (function(_super) {

      __extends(App, _super);

      function App() {
        return App.__super__.constructor.apply(this, arguments);
      }

      App.prototype.urlRoot = '/app';

      App.prototype.initialize = function(onServer) {
        var _this = this;
        this.game = new Game;
        if (onServer) {
          this.is_publishing = true;
        } else {
          this.is_publishing = false;
          this.game.bind('start', function() {
            return _this.is_publishing = true;
          });
        }
        this.game.bind('publish', function(e) {
          if (!_this.is_publishing) {
            return;
          }
          return _this.trigger('publish', {
            game: e
          });
        });
        this.bind('publish', function(e) {
          return console.log("app sending update: " + JSON.stringify(e));
        });
        return this.bind('update', function(e) {
          console.log("app getting update: " + JSON.stringify(e));
          if (e.game != null) {
            _this.game.trigger('update', e.game);
          }
          if (e.set != null) {
            return _this.set(e.set);
          }
        });
      };

      return App;

    })(Backbone.Model);
  });

}).call(this);
