// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(function(require) {
    var Entity, RelationalModel;
    RelationalModel = require('nanowar/helpers/RelationalModel');
    return Entity = (function(_super) {

      __extends(Entity, _super);

      function Entity(attributes, options) {
        if (attributes && attributes.game) {
          this.game = attributes.game;
          delete attributes.game;
        } else {
          throw "Entity needs game";
        }
        this.bind('update', function(data) {
          return this.set(data);
        });
        Entity.__super__.constructor.apply(this, arguments);
      }

      return Entity;

    })(RelationalModel);
  });

}).call(this);
